### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [minchaechoe/PY202309#3]
### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/list_and_tuple
    - 96:Statement seems to have no effect	s
    - 96:Undefined variable 's'	s
         - 완성되지 않은 코드가 있습니다. 제거해주세요. 
- WARNING in challenge/week6/function
    - 48:Undefined variable 'lotto'	lotto.sort() # sort the list by ascending order
    - 49:Undefined variable 'lotto'	for number in lotto:
        - lotto 라는 변수가 선언되어 있지 않습니다. (set_lotto_numbers()에 선언된 lotto는 지역변수로, 해당 함수가 끝나면 사라집니다) 
        - lotto 변수를 어딘가에 초기화한 후 사용하세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week4/condition
    - 추출된 주석: #   R e c e i v e   f r o m   t h e   u s e r   w h e t h e r   i t ' s   r a i n i n g   a n d   w i n d y   a n d   s t o r e   t h e   i n p u t   i n   l o w e r c a s e
- Insufficient comments in practice/week3/turtle
- Insufficient comments in project/week8/search_engine

**Comment by minchaechoe** [comment]
해결 완료했습니다.
editing previous files - Commits on Nov 7, 2023
